id: P005549
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:58:46.838703
source_metadata:
  id: bdr:W1KG21224
  title: བོད་ཀྱི་དཔྱ་ཁྲལ་གྱི་གྲོས་འདྲིའི་ལག་དེབ།
  author: ''
  volumes:
    14eb4f572eca4f2baf4ed23b352d4590:
      image_group_id: I1KG21270
      title: ''
      volume_number: 1
      total_pages: 466
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
