id: P005549
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG21224
  title: བོད་ཀྱི་དཔྱ་ཁྲལ་གྱི་གྲོས་འདྲིའི་ལག་དེབ།
  author: ''
  volumes:
    14eb4f572eca4f2baf4ed23b352d4590:
      image_group_id: I1KG21270
      title: ''
      volume_number: 1
      total_pages: 466
